---

name: CI
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 7 * * 0"

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Lint Ansible role
      uses: ansible/ansible-lint-action@v6
